apiVersion: apps/v1
kind: Deployment
metadata:
    name: canary-$CLR
spec:
    selector:
        matchLabels:
            app: canary
            env: $CLR
    replicas: 1
    template:
        metadata:
            labels:
                app: canary
                env: $CLR
        spec:
            containers:
                - name: example-api
                  imagePullPolicy: Always
                  image: kdalwadi28/nginx-$BRANCH
                  ports:
                      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: canary-$CLR-prod
spec:
#    type: NodePort
    selector:
        app: canary
        env: $CLR
    ports:
        - port: 80
          targetPort: 80
#          nodePort: $PRT
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: canary-$CLR-prod
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "$PERCENT"    
spec:
#  ingressClassName: nginx
  rules:
    - host: canary-demo.sa
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prod-$CLR
                port:
                  number: 80
#                  number: $PRT
...                  
