apiVersion: apps/v1
kind: Deployment
metadata:
    name: prod-$CLR
spec:
    selector:
        matchLabels:
            app: example
            env: $CLR
    replicas: 1
    template:
        metadata:
            labels:
                app: example
                env: $CLR
        spec:
            containers:
                - name: example-api
                  imagePullPolicy: Always
                  image: kdalwadi28/nginx-$BRANCH
                  ports:
                      - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
    name: prod-$CLR
spec:
#    type: NodePort
    selector:
        app: example
        env: $CLR
    ports:
        - port: 5000
          targetPort: 5000
#          nodePort: $PRT
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prod-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: my-nginx.info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prod-$CLR
                port:
                   number: 5000
#                  number: $PRT
...                  
