name: Changelog CI

on:
  pull_request:
    types: [ opened ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v1.1.2
        with:
          github_token: ${{ secrets.GENERATE_CHANGELOG_GITHUB_TOKEN }}



# name: Docker Image CI

# on:
#   push:
#     branches:
#       - "dev"
#   # pull_request_target:
#   #   types:
#   #     - closed

# jobs:

  # stage:
  #   if:  startsWith(github.head_ref, 'dev')
  #   runs-on: self-hosted
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Build the Docker image
  #     run: |
  #      docker build ./app/ --tag kdalwadi28/nginx-stage
  #      docker push kdalwadi28/nginx-stage
  #   - uses: actions/checkout@v3       
  #   - name: Restart K8s Deployment
  #     run: |
  #      pwd && ls
  #      export CLR=green
  #      export BRANCH=stage
  #      export PRT=30081
  #      envsubst < ./manifest.yml | kubectl apply -f -
  #      kubectl rollout restart deployment canary-green
  #      kubectl patch ingress canary-green-prod --type='json' -p='[{"op": "add", "path": "/metadata/annotations/nginx.ingress.kubernetes.io~1canary", "value":"true"}]'
  #      kubectl patch ingress canary-green-prod --type='json' -p='[{"op": "add", "path": "/metadata/annotations/nginx.ingress.kubernetes.io~1canary-weight", "value":"25"}]'
       
 
  # deploy:

  #   runs-on: self-hosted
  #   if:  startsWith(github.head_ref, 'stage')
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Build the Docker image
  #     run: |
  #      docker build ./app/ --tag kdalwadi28/nginx-prod
  #      docker push kdalwadi28/nginx-prod
  #   - uses: actions/checkout@v3
  #   - name: Restart K8s Deployment
  #     run: |
  #      pwd && ls
  #      export CLR=blue
  #      export BRANCH=prod
  #      export PRT=30080
  #      envsubst < ./manifest.yml | kubectl apply -f -
  #      kubectl rollout restart deployment canary-blue
