name: Changelog CI

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - id: 'install_python'
        name: 'Set up Python requirements'
        run: 'pip3 install -r ./scripts/requirements.txt'

      - id: 'increase_version'
        name: 'Bump version using semver'
        run: |-
          echo "NEW_IMAGE=$(python3 ./scripts/bump_version_semver.py 0.1.0 COMMIT_HEAD)" >> $GITHUB_ENV

      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v1.1.2
        with:
          github_token: ${{ secrets.GENERATE_CHANGELOG_GITHUB_TOKEN }}
          release_version: ${{ env.NEW_IMAGE }}



# name: Docker Image CI

# on:
#   push:
#     branches:
#       - "dev"
#   # pull_request_target:
#   #   types:
#   #     - closed

# jobs:

  # stage:
  #   if:  startsWith(github.head_ref, 'dev')
  #   runs-on: self-hosted
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Build the Docker image
  #     run: |
  #      docker build ./app/ --tag kdalwadi28/nginx-stage
  #      docker push kdalwadi28/nginx-stage
  #   - uses: actions/checkout@v3       
  #   - name: Restart K8s Deployment
  #     run: |
  #      pwd && ls
  #      export CLR=green
  #      export BRANCH=stage
  #      export PRT=30081
  #      envsubst < ./manifest.yml | kubectl apply -f -
  #      kubectl rollout restart deployment canary-green
  #      kubectl patch ingress canary-green-prod --type='json' -p='[{"op": "add", "path": "/metadata/annotations/nginx.ingress.kubernetes.io~1canary", "value":"true"}]'
  #      kubectl patch ingress canary-green-prod --type='json' -p='[{"op": "add", "path": "/metadata/annotations/nginx.ingress.kubernetes.io~1canary-weight", "value":"25"}]'
       
 
  # deploy:

  #   runs-on: self-hosted
  #   if:  startsWith(github.head_ref, 'stage')
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Build the Docker image
  #     run: |
  #      docker build ./app/ --tag kdalwadi28/nginx-prod
  #      docker push kdalwadi28/nginx-prod
  #   - uses: actions/checkout@v3
  #   - name: Restart K8s Deployment
  #     run: |
  #      pwd && ls
  #      export CLR=blue
  #      export BRANCH=prod
  #      export PRT=30080
  #      envsubst < ./manifest.yml | kubectl apply -f -
  #      kubectl rollout restart deployment canary-blue
